### ISSUE TITLE
Added better contributing documentation

### ISSUE THREAD

**Issue by bradleygolden** [bradleygolden/configureme#11]
The contributing documentation is lacking in some areas. There should be steps that explicitly tell contributors to do at least the following:

1. update `CONTRIBUTING.md`
2. update `versions.py` if relevant
3. update `CHANGELOG.md`

**Comment by f1x3d** [comment]
What about a [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) with the task list?
